"""
FastAPI Web Service Layer for Financial RAG Pipeline
Exposes local parent-child recursive query engine to external network calls.
"""
import os
# Force disable tokenizer parallelism to prevent macOS Uvicorn deadlocks
os.environ["TOKENIZERS_PARALLELISM"] = "false"

import chromadb
import asyncio
import random
from typing import List, Dict, Any, Optional
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field
from rich.console import Console
from rich.panel import Panel
from dotenv import load_dotenv

from llama_index.core import (
    VectorStoreIndex,
    StorageContext,
    Settings,
    Document
)
from llama_index.core.node_parser import (
    HierarchicalNodeParser,
    get_leaf_nodes,
    get_root_nodes
)
from llama_index.core.retrievers import AutoMergingRetriever
from llama_index.core.query_engine import RetrieverQueryEngine
from llama_index.vector_stores.chroma import ChromaVectorStore

# Load environment variables
load_dotenv()

# Initialize Rich Console immediately so it is defined before any log commands are executed
console = Console()

# Safety boundary: Check for either GOOGLE_API_KEY or GEMINI_API_KEY to prevent initialization failures
api_key_env = os.getenv("GOOGLE_API_KEY") or os.getenv("GEMINI_API_KEY")
if not api_key_env:
    console.print(Panel.fit(
        "[bold red]⚠️ WARNING: Gemini API Key not found in environment variables[/bold red]\n\n"
        "The API will continue to run, but queries will fail with an error message.\n"
        "Please set GOOGLE_API_KEY or GEMINI_API_KEY in your .env file or environment.",
        title="Security Alert"
    ))

# Configuration constants
CHROMA_PERSIST_DIR = "data/production/chroma_db"
CHROMA_COLLECTION_NAME = "financial_rag_collection"
STORAGE_DIR = "data/production/storage"

# Initialize FastAPI application
app = FastAPI(
    title="Financial RAG Pipeline API",
    description="Async web API gateway for financial document retrieval with parent-child recursive query engine",
    version="1.0.0",
    docs_url="/docs",
    redoc_url="/redoc"
)

# Configure CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Allow all origins for development (restrict in production)
    allow_credentials=True,
    allow_methods=["*"],  # Allow all HTTP methods
    allow_headers=["*"],  # Allow all headers
)


# Pydantic Models for Request/Response Schemas
class QueryRequest(BaseModel):
    """Structured request body for query endpoint."""
    query: str = Field(..., description="User prompt query string", min_length=1, max_length=1000)
    top_k: Optional[int] = Field(default=5, description="Number of top results to retrieve", ge=1, le=20)


class SourceNode(BaseModel):
    """Source node metadata fragment."""
    text: str = Field(..., description="Text content of the source node")
    file_name: Optional[str] = Field(None, description="Source file name")
    page_number: Optional[int] = Field(None, description="Page number in source document")
    score: Optional[float] = Field(None, description="Semantic matching score")
    metadata: Optional[Dict[str, Any]] = Field(default_factory=dict, description="Additional metadata")


class QueryResponse(BaseModel):
    """Structured response object for query endpoint."""
    response: str = Field(..., description="Textual answer generated by the pipeline")
    source_nodes: List[SourceNode] = Field(default_factory=list, description="Source metadata fragments used to construct the answer")
    query: str = Field(..., description="Original query string")
    top_k: int = Field(..., description="Number of results retrieved")


class HealthResponse(BaseModel):
    """Health check response."""
    status: str = Field(..., description="Service health status")
    version: str = Field(..., description="API version")
    chroma_connected: bool = Field(..., description="ChromaDB connection status")


# Query Engine Management
class QueryEngineManager:
    """
    Manages the lifecycle of the query engine with persistent ChromaVectorStore
    and recursive AutoMergingRetriever.
    """
    def __init__(self):
        self.index: Optional[VectorStoreIndex] = None
        self.query_engine: Optional[RetrieverQueryEngine] = None
        self._initialized = False
    
    def initialize(self):
        """Initialize the query engine from persistent storage."""
        if self._initialized:
            return
        
        console.print("[bold cyan]Initializing Global Settings & Query Engine Manager[/bold cyan]")
        
        try:
            # Lazy import to prevent top-level module blocking during Uvicorn startup
            from src.config import init_llm_and_embeddings
            init_llm_and_embeddings()
            console.print("[green]✓[/green] Global LLM and Embeddings configured successfully")

            # Setup ChromaDB vector store
            chroma_client = chromadb.PersistentClient(path=CHROMA_PERSIST_DIR)
            chroma_collection = chroma_client.get_or_create_collection(
                name=CHROMA_COLLECTION_NAME,
                metadata={"hnsw:space": "cosine"}
            )
            vector_store = ChromaVectorStore(chroma_collection=chroma_collection)
            
            # Create storage context
            storage_context = StorageContext.from_defaults(
                vector_store=vector_store,
                persist_dir=STORAGE_DIR
            )
            
            # Load index from persistent storage
            try:
                self.index = VectorStoreIndex.from_documents(
                    [],  # Empty documents, load from storage
                    storage_context=storage_context
                )
                console.print("[green]✓[/green] Index loaded from persistent storage")
            except Exception as e:
                console.print(f"[yellow]Warning:[/yellow] Could not load index from storage: {str(e)}")
                console.print("[yellow]Creating empty index for testing[/yellow]")
                self.index = VectorStoreIndex.from_documents(
                    [Document(text="Test document for API initialization")],
                    storage_context=storage_context
                )
            
            # Create base retriever
            base_retriever = self.index.as_retriever(similarity_top_k=5)
            
            # Create query engine (simplified version without AutoMerging for API safety)
            self.query_engine = RetrieverQueryEngine.from_args(
                retriever=base_retriever,
                llm=Settings.llm,
                embed_model=Settings.embed_model
            )
            
            self._initialized = True
            console.print("[green]✓[/green] Query Engine Manager initialized successfully")
            
        except Exception as e:
            console.print(f"[red]✗[/red] Error initializing Query Engine Manager: {str(e)}")
            raise
    
    async def query(self, query_text: str, top_k: int = 5) -> QueryResponse:
        """
        Execute query using the initialized query engine with live LLM generation.
        Implements exponential backoff retry with randomized jitter for rate limit handling.
        """
        if not self._initialized:
            self.initialize()
        
        # Safety boundary: Check for API key configuration
        api_key_env = os.getenv("GOOGLE_API_KEY") or os.getenv("GEMINI_API_KEY")
        if not api_key_env:
            console.print("[red]✗[/red] Gemini API key not configured")
            raise HTTPException(
                status_code=503,
                detail="Gemini API key not configured. Please set the environment variable in your .env file."
            )
        
        try:
            console.print(f"[yellow]Processing query:[/yellow] {query_text}")
            
            # Institutional Financial Analyst System Prompt
            system_prompt = """You are a Principal Institutional Financial Analyst and Forensic Risk Auditor.

Constraint 1 (Grounding): You must synthesize answers based exclusively on the verified parent-child metadata text fragments provided in the retrieved vector context chunks. Do not extrapolate, guess, or invent outside data.

Constraint 2 (Hallucination Control): If the retrieved database context does not contain sufficient quantitative or qualitative evidence to answer the user query, state explicitly: "Insufficient localized report data available to complete this calculation sequence safely."

Constraint 3 (Citation Mapping): Ensure numbers, metrics, and risk insights are directly associated with their source files and page numbers as formatted by the backend node matrix."""
            
            # Configure LLM with system prompt
            from llama_index.llms.google_genai import GoogleGenAI
            llm_with_prompt = GoogleGenAI(
                model="gemini-3.5-flash",
                api_key=api_key_env,
                system_prompt=system_prompt
            )
            
            # Update query engine with configured LLM
            self.query_engine = RetrieverQueryEngine.from_args(
                retriever=self.index.as_retriever(similarity_top_k=top_k),
                llm=llm_with_prompt,
                embed_model=Settings.embed_model
            )
            
            # Execute query asynchronously with exponential backoff retry
            max_retries = 3
            base_delay = 2.0  # Base delay in seconds
            
            for attempt in range(max_retries):
                try:
                    response = await self.query_engine.aquery(query_text)
                    break  # Success, exit retry loop
                except Exception as e:
                    # Check if this is a rate limit error (HTTP 429 or similar)
                    error_str = str(e).lower()
                    is_rate_limit = any(code in error_str for code in ['429', 'rate limit', 'quota', 'resource exhausted'])
                    
                    if is_rate_limit and attempt < max_retries - 1:
                        # Calculate exponential backoff with jitter
                        delay = base_delay * (2 ** attempt) + random.uniform(0, 1)
                        console.print(f"[yellow]⚠️ Rate limit detected. Retrying in {delay:.2f}s (Attempt {attempt + 1}/{max_retries})[/yellow]")
                        await asyncio.sleep(delay)
                    else:
                        # Not a rate limit error or max retries exceeded
                        raise
            
            # Retrieve source nodes for citation mapping
            retriever = self.index.as_retriever(similarity_top_k=top_k)
            nodes = retriever.retrieve(query_text)
            
            # Build source nodes list with metadata safely unpackaging LlamaIndex NodeWithScore wraps
            source_nodes_list = []
            for node_with_score in nodes:
                actual_node = node_with_score.node if hasattr(node_with_score, "node") else node_with_score
                score_val = getattr(node_with_score, "score", None)
                
                source_node = SourceNode(
                    text=actual_node.text,
                    file_name=actual_node.metadata.get("file_name") if actual_node.metadata else None,
                    page_number=actual_node.metadata.get("page_number") if actual_node.metadata else None,
                    score=score_val,
                    metadata=actual_node.metadata or {}
                )
                source_nodes_list.append(source_node)
            
            console.print(f"[green]✓[/green] Query processed successfully with live LLM generation")
            
            return QueryResponse(
                response=str(response),
                source_nodes=source_nodes_list,
                query=query_text,
                top_k=top_k
            )
            
        except Exception as e:
            console.print(f"[red]✗[/red] Error processing query: {str(e)}")
            raise HTTPException(status_code=500, detail=f"Query processing failed: {str(e)}")


# Global query engine manager instance
query_engine_manager = QueryEngineManager()


# API Endpoints
@app.get("/", response_model=Dict[str, str])
async def root():
    """Root endpoint with API information."""
    return {
        "message": "Financial RAG Pipeline API",
        "version": "1.0.0",
        "docs": "/docs",
        "health": "/health"
    }


@app.get("/health", response_model=HealthResponse)
async def health_check():
    """Health check endpoint."""
    try:
        # Check ChromaDB connection
        chroma_client = chromadb.PersistentClient(path=CHROMA_PERSIST_DIR)
        chroma_client.heartbeat()
        chroma_connected = True
    except Exception:
        chroma_connected = False
    
    return HealthResponse(
        status="healthy",
        version="1.0.0",
        chroma_connected=chroma_connected
    )


@app.post("/api/v1/query", response_model=QueryResponse)
async def query_endpoint(request: QueryRequest):
    """
    Query endpoint that accepts user prompt and returns structured response.
    
    Uses asynchronous hooks (aquery) to prevent thread-blocking.
    Includes safety gate for LLM generation to prevent quota exhaustion.
    """
    try:
        # Initialize query engine if not already initialized
        if not query_engine_manager._initialized:
            query_engine_manager.initialize()
        
        # Process query asynchronously
        response = await query_engine_manager.query(
            query_text=request.query,
            top_k=request.top_k
        )
        
        return response
        
    except HTTPException:
        raise
    except Exception as e:
        console.print(f"[red]✗[/red] Unexpected error in query endpoint: {str(e)}")
        raise HTTPException(status_code=500, detail=f"Internal server error: {str(e)}")


# Startup event
@app.on_event("startup")
async def startup_event():
    """Initialize query engine on startup."""
    console.print(Panel.fit(
        "[bold cyan]Financial RAG Pipeline API Starting[/bold cyan]\n"
        "[yellow]Initializing query engine manager...[/yellow]",
        title="API STARTUP"
    ))
    try:
        query_engine_manager.initialize()
        console.print("[bold green]✓ API startup completed successfully[/bold green]")
    except Exception as e:
        console.print(f"[bold red]✗ API startup failed:[/bold red] {str(e)}")


# Shutdown event
@app.on_event("shutdown")
async def shutdown_event():
    """Cleanup on shutdown."""
    console.print("[yellow]API shutting down...[/yellow]")


if __name__ == "__main__":
    import uvicorn
    console.print(Panel.fit(
        "[bold cyan]Starting Financial RAG Pipeline API Server[/bold cyan]\n"
        "[yellow]Server will be available at:[/yellow] http://localhost:8000\n"
        "[yellow]API Documentation:[/yellow] http://localhost:8000/docs",
        title="SERVER START"
    ))
    uvicorn.run(
        "src.app:app",
        host="0.0.0.0",
        port=8000,
        reload=False,
        log_level="info"
    )